### ISSUE TITLE
Failed to load plugin due to error: Failed to acquire unique machine id.

### ISSUE THREAD

**Issue by ghostzero** [own3d/own3dpro-obs-plugin#10]
### Description

Sometimes users have the problem that their plugin does not load because no machine key could be acquired.

To be able to answer support requests more specifically it would be helpful if:

- Users get a dialog if the machine token could not be requested.
- More debug details are provided in the log. E.g. Cause: HTTP or SSL Error, etc.

```
17:53:16.120: [Own3d.TV] Attempt 0 at retrieving a unique machine id failed.
...
17:53:17.754: [Own3d.TV] Attempt 9 at retrieving a unique machine id failed.
17:53:17.855: [Own3d.TV] Failed to acquire unique machine id, error code 35. Functionality disabled.
17:53:17.855: [Own3d.TV] Failed to load plugin due to error: Failed to acquire unique machine id.
```

### System Information
https://obsproject.com/logs/RwJhcCmIG58eHXRU

**Comment by PassiHD2004** [comment]
do you know any fix for that?

**Comment by ghostzero** [comment]
Unfortunately, we don't have any updates for that. Do you have any anti-virus software active? Or a VPN, proxy active? Or is your ping to own3d.pro too high?

**Comment by ghostzero** [comment]
Update: Apparently the Windows firewall is giving us problems. We will adjust the license process so that this step (async) is tried several times for a maximum of one minute.

**Comment by alruiz95** [comment]
I got Exactly the same issue, my log file:


`20:36:53.501: CPU Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
20:36:53.501: CPU Speed: 2808MHz
20:36:53.501: Physical Cores: 4, Logical Cores: 8
20:36:53.501: Physical Memory: 16303MB Total, 10842MB Free
20:36:53.501: Windows Version: 10.0 Build 19044 (release: 2009; revision: 1706; 64-bit)
20:36:53.501: Running as administrator: false
20:36:53.501: Aero is Enabled (Aero is always on for windows 8 and above)
20:36:53.501: Windows 10 Gaming Features:
20:36:53.501: 	Game DVR: On
20:36:53.504: Sec. Software Status:
20:36:53.506: 	Microsoft Defender Antivirus: enabled (AV)
20:36:53.507: 	Windows Firewall: disabled (FW)
20:36:53.508: Current Date/Time: 2022-05-24, 20:36:53
20:36:53.508: Browser Hardware Acceleration: true
20:36:53.508: Hide OBS windows from screen capture: false
20:36:53.508: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
20:36:53.508: Portable mode: false
20:36:53.768: OBS 27.2.4 (64-bit, windows)
20:36:53.768: ---------------------------------
20:36:53.769: ---------------------------------
20:36:53.769: audio settings reset:
20:36:53.769: 	samples per sec: 48000
20:36:53.769: 	speakers:        2
20:36:53.771: ---------------------------------
20:36:53.771: Initializing D3D11...
20:36:53.771: Available Video Adapters: 
20:36:53.784: 	Adapter 0: NVIDIA GeForce GTX 1050
20:36:53.784: 	  Dedicated VRAM: 4216324096
20:36:53.784: 	  Shared VRAM:    4252889088
20:36:53.784: 	  PCI ID:         10de:1c8d
20:36:53.784: 	  Driver Version: 30.0.15.1295
20:36:53.784: 	  output 0:
20:36:53.784: 	    name=
20:36:53.784: 	    pos={0, 0}
20:36:53.784: 	    size={1920, 1080}
20:36:53.784: 	    attached=true
20:36:53.784: 	    refresh=60
20:36:53.784: 	    space=RGB_FULL_G22_NONE_P709
20:36:53.784: 	    sdr_white_nits=80
20:36:53.784: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
20:36:53.785: 	Adapter 1: Intel(R) HD Graphics 630
20:36:53.785: 	  Dedicated VRAM: 134217728
20:36:53.785: 	  Shared VRAM:    4252889088
20:36:53.785: 	  PCI ID:         8086:591b
20:36:53.785: 	  Driver Version: 27.20.100.7989
20:36:53.794: Loading up D3D11 on adapter NVIDIA GeForce GTX 1050 (0)
20:36:54.854: D3D11 loaded successfully, feature level used: b000
20:36:54.854: DXGI increase maximum frame latency success
20:36:54.854: D3D11 GPU priority setup failed (not admin?)
20:36:55.342: ---------------------------------
20:36:55.342: video settings reset:
20:36:55.342: 	base resolution:   1920x1080
20:36:55.342: 	output resolution: 1280x720
20:36:55.342: 	downscale filter:  Bicubic
20:36:55.342: 	fps:               30/1
20:36:55.342: 	format:            NV12
20:36:55.342: 	YUV mode:          709/Partial
20:36:55.342: NV12 texture support enabled
20:36:55.344: Audio monitoring device:
20:36:55.344: 	name: Default
20:36:55.344: 	id: default
20:36:55.345: ---------------------------------
20:36:55.348: No AJA devices found, skipping loading AJA UI plugin
20:36:55.349: Failed to initialize module 'aja-output-ui.dll'
20:36:55.351: No AJA devices found, skipping loading AJA plugin
20:36:55.351: Failed to initialize module 'aja.dll'
20:36:55.351: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
20:36:55.353: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
20:36:55.354: Failed to load 'en-US' text for module: 'decklink-captions.dll'
20:36:55.355: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
20:36:55.397: [AMF] Unable to load 'amfrt64.dll', error code 126.
20:36:55.400: [AMF] AMF Test failed due to one or more errors.
20:36:55.400: Failed to initialize module 'enc-amf.dll'
20:36:55.411: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
20:36:55.411: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
20:36:55.411: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
20:36:55.423: [obs-browser]: Version 2.17.13
20:36:55.423: [obs-browser]: CEF Version 95.0.0-MediaHandler.2467+g8092a57+chromium-95.0.4638.69
20:36:55.426: NVENC supported
20:36:55.427: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
20:36:58.058: [Own3d.TV] Attempt 0 at retrieving a unique machine id failed.
20:36:58.538: [Own3d.TV] Attempt 1 at retrieving a unique machine id failed.
20:36:59.040: [Own3d.TV] Attempt 2 at retrieving a unique machine id failed.
20:36:59.521: [Own3d.TV] Attempt 3 at retrieving a unique machine id failed.
20:37:00.006: [Own3d.TV] Attempt 4 at retrieving a unique machine id failed.
20:37:00.484: [Own3d.TV] Attempt 5 at retrieving a unique machine id failed.
20:37:00.980: [Own3d.TV] Attempt 6 at retrieving a unique machine id failed.
20:37:01.458: [Own3d.TV] Attempt 7 at retrieving a unique machine id failed.
20:37:01.925: [Own3d.TV] Attempt 8 at retrieving a unique machine id failed.
20:37:02.405: [Own3d.TV] Attempt 9 at retrieving a unique machine id failed.
20:37:02.506: [Own3d.TV] Failed to acquire unique machine id, error code 35. Functionality disabled.
20:37:02.506: [Own3d.TV] Failed to load plugin due to error: Failed to acquire unique machine id.
20:37:02.506: Failed to initialize module 'own3d.dll'
20:37:02.519: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
20:37:02.537: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
20:37:02.540: No blackmagic support
20:37:02.551: Skipping module '../../obs-plugins/64bit/zip.dll', not an OBS plugin
20:37:02.552: ---------------------------------
20:37:02.552:   Loaded Modules:
20:37:02.552:     win-wasapi.dll
20:37:02.552:     win-mf.dll
20:37:02.552:     win-dshow.dll
20:37:02.552:     win-decklink.dll
20:37:02.552:     win-capture.dll
20:37:02.552:     vlc-video.dll
20:37:02.552:     text-freetype2.dll
20:37:02.552:     rtmp-services.dll
20:37:02.552:     obs-x264.dll
20:37:02.552:     obs-vst.dll
20:37:02.552:     obs-transitions.dll
20:37:02.552:     obs-text.dll
20:37:02.552:     obs-qsv11.dll
20:37:02.552:     obs-outputs.dll
20:37:02.552:     obs-filters.dll
20:37:02.552:     obs-ffmpeg.dll
20:37:02.552:     obs-browser.dll
20:37:02.552:     image-source.dll
20:37:02.552:     frontend-tools.dll
20:37:02.552:     decklink-ouput-ui.dll
20:37:02.552:     decklink-captions.dll
20:37:02.552:     coreaudio-encoder.dll
20:37:02.552: ---------------------------------
20:37:02.553: ==== Startup complete ===============================================
20:37:02.616: All scene data cleared
20:37:02.616: ------------------------------------------------
20:37:02.626: [win-wasapi: 'Desktop Audio'] update settings:
20:37:02.626: 	device id: default
20:37:02.626: 	use device timing: 1
20:37:02.636: [Loaded global audio device]: 'Desktop Audio'
20:37:02.637: [win-wasapi: 'Mic/Aux'] update settings:
20:37:02.637: 	device id: default
20:37:02.637: 	use device timing: 0
20:37:02.637: [Loaded global audio device]: 'Mic/Aux'
20:37:02.637: Switched to scene 'Scene'
20:37:02.637: ------------------------------------------------
20:37:02.637: Loaded scenes:
20:37:02.637: - scene 'Scene':
20:37:02.637: ------------------------------------------------
20:37:02.677: WASAPI: Device 'Microphone (T2S Webcam)' [16000 Hz] initialized
20:37:02.713: WASAPI: Device 'Speakers (Realtek High Definition Audio)' [48000 Hz] initialized
20:37:45.178: ==== Shutting down ==================================================
20:37:45.183: WASAPI: Device 'Speakers (Realtek High Definition Audio)' Terminated
20:37:45.186: WASAPI: Device 'Microphone (T2S Webcam)' Terminated
20:37:45.226: All scene data cleared
20:37:45.226: ------------------------------------------------
20:37:45.394: [Scripting] Total detached callbacks: 0
20:37:45.394: Freeing OBS context data
20:37:45.426: == Profiler Results =============================
20:37:45.426: run_program_init: 9351.63 ms
20:37:45.426:  ┣OBSApp::AppInit: 25.256 ms
20:37:45.426:  ┃ ┗OBSApp::InitLocale: 1.571 ms
20:37:45.426:  ┗OBSApp::OBSInit: 9303.86 ms
20:37:45.426:    ┣obs_startup: 7.088 ms
20:37:45.426:    ┗OBSBasic::OBSInit: 9035.65 ms
20:37:45.426:      ┣OBSBasic::InitBasicConfig: 0.446 ms
20:37:45.426:      ┣OBSBasic::ResetAudio: 0.169 ms
20:37:45.426:      ┣OBSBasic::ResetVideo: 1574.96 ms
20:37:45.426:      ┣OBSBasic::InitOBSCallbacks: 0.025 ms
20:37:45.426:      ┣OBSBasic::InitHotkeys: 0.058 ms
20:37:45.426:      ┣obs_load_all_modules: 7207.25 ms
20:37:45.426:      ┃ ┣obs_init_module(aja-output-ui.dll): 1.076 ms
20:37:45.426:      ┃ ┣obs_init_module(aja.dll): 0.153 ms
20:37:45.426:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 1.317 ms
20:37:45.426:      ┃ ┣obs_init_module(decklink-captions.dll): 0.027 ms
20:37:45.426:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 1.13 ms
20:37:45.426:      ┃ ┣obs_init_module(enc-amf.dll): 42.954 ms
20:37:45.426:      ┃ ┣obs_init_module(frontend-tools.dll): 7.076 ms
20:37:45.426:      ┃ ┣obs_init_module(image-source.dll): 0.006 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-browser.dll): 0.464 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 0.846 ms
20:37:45.426:      ┃ ┃ ┗nvenc_check: 0.568 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-filters.dll): 0.042 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-outputs.dll): 0.011 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-qsv11.dll): 58.493 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-text.dll): 0.261 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-transitions.dll): 0.01 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-vst.dll): 0.002 ms
20:37:45.426:      ┃ ┣obs_init_module(obs-x264.dll): 0.002 ms
20:37:45.426:      ┃ ┣obs_init_module(own3d.dll): 6969.39 ms
20:37:45.426:      ┃ ┣obs_init_module(rtmp-services.dll): 4.371 ms
20:37:45.426:      ┃ ┣obs_init_module(text-freetype2.dll): 0.175 ms
20:37:45.426:      ┃ ┣obs_init_module(vlc-video.dll): 0.129 ms
20:37:45.427:      ┃ ┣obs_init_module(win-capture.dll): 4.923 ms
20:37:45.427:      ┃ ┣obs_init_module(win-decklink.dll): 10.723 ms
20:37:45.427:      ┃ ┣obs_init_module(win-dshow.dll): 4.78 ms
20:37:45.427:      ┃ ┣obs_init_module(win-mf.dll): 0 ms
20:37:45.427:      ┃ ┣obs_init_module(win-wasapi.dll): 0.023 ms
20:37:45.427:      ┃ ┗reset_win32_symbol_paths: 0.795 ms
20:37:45.427:      ┣OBSBasic::ResetOutputs: 0.639 ms
20:37:45.427:      ┣OBSBasic::CreateHotkeys: 0.093 ms
20:37:45.427:      ┣OBSBasic::InitService: 2.909 ms
20:37:45.427:      ┣OBSBasic::InitPrimitives: 0.159 ms
20:37:45.427:      ┗OBSBasic::Load: 75.052 ms
20:37:45.427: obs_hotkey_thread(25 ms): min=0.004 ms, median=0.01 ms, max=0.432 ms, 99th percentile=0.209 ms, 100% below 25 ms
20:37:45.427: audio_thread(Audio): min=0 ms, median=0.02 ms, max=0.104 ms, 99th percentile=0.063 ms
20:37:45.427: obs_graphics_thread(33.3333 ms): min=0.119 ms, median=1.062 ms, max=20.163 ms, 99th percentile=2.219 ms, 100% below 33.333 ms
20:37:45.427:  ┣tick_sources: min=0.001 ms, median=0.006 ms, max=0.059 ms, 99th percentile=0.027 ms
20:37:45.427:  ┣output_frame: min=0.088 ms, median=0.177 ms, max=1.115 ms, 99th percentile=0.373 ms
20:37:45.427:  ┃ ┗gs_context(video->graphics): min=0.087 ms, median=0.177 ms, max=1.112 ms, 99th percentile=0.372 ms
20:37:45.427:  ┃   ┣render_video: min=0.005 ms, median=0.008 ms, max=0.087 ms, 99th percentile=0.04 ms
20:37:45.427:  ┃   ┃ ┗render_main_texture: min=0.002 ms, median=0.005 ms, max=0.084 ms, 99th percentile=0.024 ms
20:37:45.427:  ┃   ┗gs_flush: min=0.08 ms, median=0.168 ms, max=1.044 ms, 99th percentile=0.341 ms
20:37:45.427:  ┗render_displays: min=0.001 ms, median=0.867 ms, max=19.741 ms, 99th percentile=1.849 ms
20:37:45.427: =================================================
20:37:45.427: == Profiler Time Between Calls ==================
20:37:45.427: obs_hotkey_thread(25 ms): min=24.944 ms, median=25.859 ms, max=26.122 ms, 36.5793% within ±2% of 25 ms (0% lower, 63.4207% higher)
20:37:45.427: obs_graphics_thread(33.3333 ms): min=18.135 ms, median=33.333 ms, max=48.531 ms, 99.7333% within ±2% of 33.333 ms (0.133333% lower, 0.133333% higher)
20:37:45.427: =================================================
20:37:45.646: Number of memory leaks: 2
`

**Comment by djasuncion** [comment]
just experienced this on Windows 11, with OBS 29
